apiVersion: v1
kind: Secret
metadata:
  name: grape-db-secret
stringData:
  POSTGRES_PASSWORD: grape
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grape-db-config
data:
  POSTGRES_DB: grape
  POSTGRES_USER: grape
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grape-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grape-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grape-db
  template:
    metadata:
      labels:
        app: grape-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: grape-db-config
            - secretRef:
                name: grape-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grape-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grape-db
spec:
  selector:
    app: grape-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
